name: Docker Image CI

on:
  push:

jobs:

  build:
    if: github.repository == 'buschlab/fhirspark'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/buschlab/fhirspark:latest --label maintainer="Niklas Reimer <${{ secrets.EMAIL }}>"
    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Docker image
      run: docker push ghcr.io/buschlab/fhirspark:latest
