# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:

    services:
      hapiserver:
        image: hapiproject/hapi:v5.2.1
        ports:
         - 8080:8080
        env:
          hapi.fhir.validation.requests_enabled: 'false'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build with Maven
      run: mvn -B -Dfhir.test.url="http://localhost:8080/fhir/" package --file pom.xml
