# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    services:
      hapiserver:
        image: hapiproject/hapi:v8.0.0
        ports:
         - 8080:8080
        env:
          hapi.fhir.validation.requests_enabled: 'false'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
    - name: Run first query on FHIR server
      run: sleep 45 && curl http://localhost:8080/fhir/Patient
    - name: Build with Maven
      run: mvn -B -Dfhir.test.url="http://localhost:8080/fhir/" package --file pom.xml
