name: SonarCloud

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  sonar:
      name: Test - SonarCloud Scan
      if: github.repository == 'nr23730/fhirspark'
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            java-version: 21
            distribution: 'adopt'
        - name: SonarCloud Scan
          run: mvn -B clean verify sonar:sonar -DskipTests=true -Dsonar.organization=nr23730 -Dsonar.projectKey=nr23730_fhirspark -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}